version: '3.8'

services:
  live-dl:
    image: ghcr.io/nijinogg/live-dl:latest
    container_name: live-dl
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
    volumes:
      - ./downloads:/app/downloads
      - ./cookies.txt:/app/cookies.txt:ro
      - ./monitor_and_download.py:/app/monitor_and_download.py
    restart: unless-stopped
